### ISSUE TITLE
Separate model logic from game objects

### ISSUE THREAD

**Issue by david-pfx** [grantmoore3d/unity-package-library-CubeCoordinates#4]
The current structure imposes a certain kind of game object, which does not suit every project. This library would be more usable if it used a View-Model abstraction, in which the model has the hex grid logic and the view has the game objects.

Also consider allowing users to supply their own container structure. Some more ways to construct grids would be good too.

**Comment by owmo-dev** [comment]
Complete refactored the project to be a bit more flexible, you should be able to:

- Specify your own GameObject (prefab) to be instantiated, or just choose None and manage your own assets
- Ignore the containers if you wish (the Coordinates class will still use it by default, but otherwise not necessary)
- Ignore Coordinates altogether and simply use the Cubes static class for direct coordinate calculations

Anyhow, was fun making it a bit more useful for anyone who cares to use it. Probably won't do much more to the project unless my gamedev hobby project requires it. Hope y'all enjoy!
